---
acquia/drupal-spec-tool:
  type: behat-extension

acquia/lightning:
  type: drupal-profile
  version: 4.x
  version_dev: 4.x-dev

# Let Lightning manage its own components.
drupal/lightning_api: ~
drupal/lightning_core: ~
drupal/lightning_layout: ~
drupal/lightning_media: ~
drupal/lightning_workflow: ~
